version: '3'

services:
  personal_website:
    build: .
    container_name: personal_website
    ports:
      - "3000:3000"
    restart: unless-stopped
  
  caddy:
    image: caddy:2
    container_name: reverse_proxy
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - personal_website

volumes:
  caddy_data:
  caddy_config: